name: 'Code validation'
on: [push, pull_request]

jobs:
  linter:
    name: 'Linter'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: 'Install dependencies'
        run: npm install
      - name: 'Run linter'
        run: npm run eslint

  tests:
    name: 'Selenium tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: 'Install dependencies'
        run: sudo apt install -y python3-selenium python3-pytest chromium-driver
      - name: 'Run tests'
        run: pytest-3 -l -v -s tests/
