name: 'Code validation'
on: [push, pull_request]

jobs:
  linter:
    name: 'Linter'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: 'Install dependencies'
        run: yarn

      - name: 'Run linter'
        run: yarn run eslint

  tests:
    name: 'Selenium tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: x64

      - name: 'Install dependencies'
        run: sudo apt install -y python3-selenium python3-pytest chromium-driver

      - name: 'Run tests'
        run: pytest-3 || pytest-3 --lf --lfnf none
